pull_request_rules:
  - name: automatic merge when CI passes and 1 review
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Travis CI - Pull Request
      - base=master
    actions:
      merge:
        method: merge
  - name: automatic merge for Contributors on the test branch
    conditions:
      - status-success=Travis CI - Pull Request
      - base=dev
      - author=@developy-dev/contributors
    actions:
      merge:
        method: merge
